In [1]:
import numpy as np

In [2]:
oneD_arr = np.array([1])
oneD_arr

array([1])

In [3]:
twoD_arr = np.array([[1, 2, 3], [4, 5, 6]])
twoD_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
threeD_arr = np.array([[[10, 12, 14], [16, 18, 20], [22, 24, 26]],
                       [[28, 30, 32], [34, 36, 38], [40, 42, 44]],
                       [[48, 50, 52], [54, 56, 58], [60, 62, 64]]])

threeD_arr

array([[[10, 12, 14],
        [16, 18, 20],
        [22, 24, 26]],

       [[28, 30, 32],
        [34, 36, 38],
        [40, 42, 44]],

       [[48, 50, 52],
        [54, 56, 58],
        [60, 62, 64]]])

In [5]:
np.random.seed(100)

random_threeDim = np.random.randint(100, size=(3,3))
random_threeDim

array([[ 8, 24, 67],
       [87, 79, 48],
       [10, 94, 52]])

In [6]:
oneD_arr.shape, oneD_arr.ndim, oneD_arr.dtype

((1,), 1, dtype('int64'))

In [7]:
twoD_arr.shape, twoD_arr.ndim, twoD_arr.dtype

((2, 3), 2, dtype('int64'))

In [8]:
threeD_arr.shape, threeD_arr.ndim, threeD_arr.dtype

((3, 3, 3), 3, dtype('int64'))

In [9]:
import pandas as pd

oneD_dataF = pd.DataFrame([oneD_arr])

oneD_dataF

0
0  1

In [10]:
ones_array = np.ones([10, 2])
ones_array

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [11]:
zero_array = np.zeros([7, 2, 3])
zero_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [12]:
arange_array = np.arange(0, 100, 3)
arange_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [13]:
random_num_arr = np.random.randint(10, size=(7, 2))
random_num_arr

array([[2, 5],
       [2, 2],
       [2, 1],
       [0, 8],
       [4, 0],
       [9, 6],
       [2, 4]])

In [17]:
random_float_arr = np.random.rand(3, 5)
random_float_arr

array([[0.12665424, 0.07898787, 0.31135313, 0.63238359, 0.69935892],
       [0.64196495, 0.92002378, 0.29887635, 0.56874553, 0.17862432],
       [0.5325737 , 0.64669147, 0.14206538, 0.58138896, 0.47918994]])