In [1]:
import numpy as np

In [2]:
oneD_arr = np.array([1])
oneD_arr

array([1])

In [3]:
twoD_arr = np.array([[1, 2, 3], [4, 5, 6]])
twoD_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
threeD_arr = np.array([[[10, 12, 14], [16, 18, 20], [22, 24, 26]],
                       [[28, 30, 32], [34, 36, 38], [40, 42, 44]],
                       [[48, 50, 52], [54, 56, 58], [60, 62, 64]]])

threeD_arr

array([[[10, 12, 14],
        [16, 18, 20],
        [22, 24, 26]],

       [[28, 30, 32],
        [34, 36, 38],
        [40, 42, 44]],

       [[48, 50, 52],
        [54, 56, 58],
        [60, 62, 64]]])

In [5]:
np.random.seed(100)

random_threeDim = np.random.randint(100, size=(3,3))
random_threeDim

array([[ 8, 24, 67],
       [87, 79, 48],
       [10, 94, 52]])