## Numpy Notebook:

Topics:
1. Useful Functions
2. NumPy datatypes and Attributes (ndarray)
3. creating arrays
4. viewing arrays and matrices
5. manipulating and comparing arrays
6. sorting arrays
7. use cases

In [93]:
import numpy as np

## Datatypes and Attributes:

In [2]:
# Numpy's main datatype is ndarray!

a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2.0, 3.3],
               [4.1, 5, 6.5]])

a3 = np.array([[[1, 2, 3], [4, 5, 6]],
               [[7, 8, 9], [10, 11, 12]],
               [[13, 14, 15], [16, 17, 18]]])


a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4.1, 5. , 6.5]])

In [6]:
# attributes:

a1.shape

(3,)

In [7]:
a2.shape

(2, 3)

In [8]:
a3.shape

(3, 2, 3)

In [9]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [10]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [11]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [12]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

## Create a Dataframe from a Numpy Array

In [14]:
import pandas as pd

df = pd.DataFrame(a2)

In [15]:
df

0    1    2
0  1.0  2.0  3.3
1  4.1  5.0  6.5

## Creating Random Arrays ASAP

In [16]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [17]:
sample_array.dtype

dtype('int64')

In [18]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
ones.dtype

dtype('float64')

In [20]:
type(ones)

numpy.ndarray

In [21]:
zeros = np.zeros((2, 3))

In [22]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [24]:
random_array = np.random.randint(0, 100, size=(3, 5))
random_array

array([[80,  9, 28, 61, 64],
       [31, 71, 55, 67, 90],
       [ 1, 31, 47,  9, 29]])

In [25]:
random_array.size

15

In [26]:
random_array.shape

(3, 5)

In [27]:
random_float_arr = np.random.random((5, 3))
random_float_arr

array([[0.94432004, 0.36293965, 0.55601373],
       [0.67845962, 0.93264824, 0.36555396],
       [0.07159325, 0.51646721, 0.01215473],
       [0.06728505, 0.93972672, 0.90492222],
       [0.10749   , 0.96054391, 0.6989667 ]])

In [28]:
random_float_arr.shape

(5, 3)

In [29]:
random_float_arr_new = np.random.rand(5, 3)
random_float_arr_new

array([[0.78029385, 0.08851728, 0.9515751 ],
       [0.4952179 , 0.39493925, 0.57410193],
       [0.9880421 , 0.50195954, 0.96435633],
       [0.56391889, 0.29388746, 0.95478074],
       [0.2727698 , 0.16663776, 0.10875023]])

In [30]:
# Pseudo Random numbers:
np.random.seed(seed = 0)

In [31]:
np.random.seed(seed = 0) # now our "random" data doesnt change
random_arr_4 = np.random.randint(10, size=(5, 3))
random_arr_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [32]:
random_arr_4.shape

(5, 3)

np.random.seed() helps us to reproduce our random numbers and get same results even if someone else tries to run our notebook

In [33]:
np.random.seed(7)
random_arr_5 = np.random.random((5, 3))
random_arr_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [34]:
random_arr_5 = np.random.random((5, 3))
random_arr_5

# we observe different values

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])

## Viewing Arrays and Matrices

In [35]:
# Finding unique numbers in our ndarray

np.unique(random_arr_4)  # we get 0 to 9 as we have specified upper limit as 10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
a1

array([1, 2, 3])

In [37]:
a2

array([[1. , 2. , 3.3],
       [4.1, 5. , 6.5]])

In [38]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [39]:
a1[0]

1

In [40]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
a2[0]

array([1. , 2. , 3.3])

In [42]:
a2[1]

array([4.1, 5. , 6.5])

In [43]:
a3[2]

array([[13, 14, 15],
       [16, 17, 18]])

In [44]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [45]:
a3.shape

(3, 2, 3)

In [46]:
a3[:3,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]],

       [[13, 14],
        [16, 17]]])

array = np.rand.randint(upper-limit_of_num, size=(2 sets of final matrices ,three_matrices in one bracket ,rows ,cols))

In [47]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))

a4

array([[[[6, 7, 7, 9, 3],
         [0, 7, 7, 7, 0],
         [5, 4, 3, 1, 3],
         [1, 3, 4, 3, 1]],

        [[9, 5, 9, 1, 2],
         [3, 2, 2, 5, 7],
         [3, 0, 9, 9, 3],
         [4, 5, 3, 0, 4]],

        [[8, 6, 7, 2, 7],
         [3, 8, 6, 6, 5],
         [6, 5, 7, 1, 5],
         [4, 4, 9, 9, 0]]],


       [[[6, 2, 6, 8, 2],
         [4, 1, 6, 1, 5],
         [1, 6, 9, 8, 6],
         [5, 9, 7, 5, 4]],

        [[9, 6, 8, 1, 5],
         [5, 8, 3, 7, 7],
         [9, 4, 7, 5, 9],
         [6, 2, 0, 5, 3]],

        [[0, 5, 7, 1, 8],
         [4, 9, 0, 2, 0],
         [7, 6, 2, 9, 9],
         [5, 1, 0, 0, 9]]]])

In [48]:
a4.shape

(2, 3, 4, 5)

In [49]:
a4.ndim

4

In [50]:
# get first 4 numbers of the innermost arrays:

a4[:, :, :, :4]

array([[[[6, 7, 7, 9],
         [0, 7, 7, 7],
         [5, 4, 3, 1],
         [1, 3, 4, 3]],

        [[9, 5, 9, 1],
         [3, 2, 2, 5],
         [3, 0, 9, 9],
         [4, 5, 3, 0]],

        [[8, 6, 7, 2],
         [3, 8, 6, 6],
         [6, 5, 7, 1],
         [4, 4, 9, 9]]],


       [[[6, 2, 6, 8],
         [4, 1, 6, 1],
         [1, 6, 9, 8],
         [5, 9, 7, 5]],

        [[9, 6, 8, 1],
         [5, 8, 3, 7],
         [9, 4, 7, 5],
         [6, 2, 0, 5]],

        [[0, 5, 7, 1],
         [4, 9, 0, 2],
         [7, 6, 2, 9],
         [5, 1, 0, 0]]]])

In [51]:
a4[:, :, :, :3]

array([[[[6, 7, 7],
         [0, 7, 7],
         [5, 4, 3],
         [1, 3, 4]],

        [[9, 5, 9],
         [3, 2, 2],
         [3, 0, 9],
         [4, 5, 3]],

        [[8, 6, 7],
         [3, 8, 6],
         [6, 5, 7],
         [4, 4, 9]]],


       [[[6, 2, 6],
         [4, 1, 6],
         [1, 6, 9],
         [5, 9, 7]],

        [[9, 6, 8],
         [5, 8, 3],
         [9, 4, 7],
         [6, 2, 0]],

        [[0, 5, 7],
         [4, 9, 0],
         [7, 6, 2],
         [5, 1, 0]]]])

In [52]:
a4[:, :, :, :1]

array([[[[6],
         [0],
         [5],
         [1]],

        [[9],
         [3],
         [3],
         [4]],

        [[8],
         [3],
         [6],
         [4]]],


       [[[6],
         [4],
         [1],
         [5]],

        [[9],
         [5],
         [9],
         [6]],

        [[0],
         [4],
         [7],
         [5]]]])

## Manipulating & Comparing Arrays:

1. Arithmetic:

In [53]:
a1

array([1, 2, 3])

In [54]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [55]:
a1 + ones

array([[2., 3., 4.],
       [2., 3., 4.]])

In [56]:
a1 - ones

array([[0., 1., 2.],
       [0., 1., 2.]])

In [57]:
a1 * ones

array([[1., 2., 3.],
       [1., 2., 3.]])

In [58]:
a2

array([[1. , 2. , 3.3],
       [4.1, 5. , 6.5]])

In [59]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4.1, 10. , 19.5]])

In [60]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [61]:
a2 * a3 

array([[[  1. ,   4. ,   9.9],
        [ 16.4,  25. ,  39. ]],

       [[  7. ,  16. ,  29.7],
        [ 41. ,  55. ,  78. ]],

       [[ 13. ,  28. ,  49.5],
        [ 65.6,  85. , 117. ]]])

In [62]:
a3.shape

(3, 2, 3)

In [63]:
a2.shape

(2, 3)

When operating on two Arrays, NumPy compares their shapes elementwise.

It starts with the trailing dimensions, and works its way forward. 

Two dimensions are compatible when:

1. They are equal, or
2. one of them is 1

In [64]:
# reshape numpy array:

a_diffDim = np.array([[[1,2,3], [4,5,6], [7,8,9]],
                     [10,11,12], [13,14,15], [16,17,18]])

a_diffDim

/var/folders/m_/b2znwxkd3f18mmz8j9mdf4xh0000gn/T/ipykernel_1907/2191409259.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a_diffDim = np.array([[[1,2,3], [4,5,6], [7,8,9]],


array([[list([1, 2, 3]), list([4, 5, 6]), list([7, 8, 9])],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]], dtype=object)

Note: RESHAPE()

array_new = np.reshape(array_old, (dimensions to change into))

In [65]:
a3_reshape = np.reshape(a3, (2, 3, 3))

a3_reshape

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [66]:
a3.shape

(3, 2, 3)

In [67]:
a3_reshape.shape

(2, 3, 3)

Division And Floor Division

In [68]:
a1 / ones

array([[1., 2., 3.],
       [1., 2., 3.]])

In [69]:
a2 / a1

array([[1.        , 1.        , 1.1       ],
       [4.1       , 2.5       , 2.16666667]])

In [70]:
# floor division removes the decimals aka Rounds Down

a2 // a2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [71]:
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [72]:
a2 ** 2 # to the power of 2

array([[ 1.  ,  4.  , 10.89],
       [16.81, 25.  , 42.25]])

In [73]:
a3 ** 2

array([[[  1,   4,   9],
        [ 16,  25,  36]],

       [[ 49,  64,  81],
        [100, 121, 144]],

       [[169, 196, 225],
        [256, 289, 324]]])

In [74]:
a3_reshape ** 3

array([[[   1,    8,   27],
        [  64,  125,  216],
        [ 343,  512,  729]],

       [[1000, 1331, 1728],
        [2197, 2744, 3375],
        [4096, 4913, 5832]]])

In [75]:
# or:

np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.81, 25.  , 42.25]])

In [76]:
np.add(a1, ones)

array([[2., 3., 4.],
       [2., 3., 4.]])

In [77]:
# %-> modulo shows us the reminders

a1 % 2

array([1, 0, 1])

In [78]:
a3 % 5

array([[[1, 2, 3],
        [4, 0, 1]],

       [[2, 3, 4],
        [0, 1, 2]],

       [[3, 4, 0],
        [1, 2, 3]]])

In [79]:
a2 % 2

array([[1. , 0. , 1.3],
       [0.1, 1. , 0.5]])

In [80]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [81]:
np.exp(a3)

array([[[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
        [5.45981500e+01, 1.48413159e+02, 4.03428793e+02]],

       [[1.09663316e+03, 2.98095799e+03, 8.10308393e+03],
        [2.20264658e+04, 5.98741417e+04, 1.62754791e+05]],

       [[4.42413392e+05, 1.20260428e+06, 3.26901737e+06],
        [8.88611052e+06, 2.41549528e+07, 6.56599691e+07]]])

In [85]:
np.log(a3)

array([[[0.        , 0.69314718, 1.09861229],
        [1.38629436, 1.60943791, 1.79175947]],

       [[1.94591015, 2.07944154, 2.19722458],
        [2.30258509, 2.39789527, 2.48490665]],

       [[2.56494936, 2.63905733, 2.7080502 ],
        [2.77258872, 2.83321334, 2.89037176]]])

In [84]:
np.log(a2)

array([[0.        , 0.69314718, 1.19392247],
       [1.41098697, 1.60943791, 1.87180218]])

## Aggregation

In [86]:
# aggregation = performing the same operation on ndarray

In [87]:
listy_list = [1, 2, 3]
type(listy_list)

list

In [88]:
sum(listy_list)

6

In [89]:
type(a1)

numpy.ndarray

In [90]:
np.sum(a1)

6

use python's methods (`sum()`) on python datatypes and use Numpy's methods on NumPy Arrays (`np.sum()`)

In [91]:
# Create massive numpy array

massive_array = np.random.random(100000)

massive_array.size

100000

In [92]:
massive_array[:10]

array([0.62342345, 0.62955693, 0.9099729 , 0.96251949, 0.5850998 ,
       0.16489774, 0.39159332, 0.94455493, 0.34339118, 0.70507037])

In [94]:
%timeit sum(massive_array)     # Python's sum()

%timeit np.sum(massive_array)     # NumPy's sum()

7.14 ms ± 136 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
38.7 µs ± 298 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [95]:
a2

array([[1. , 2. , 3.3],
       [4.1, 5. , 6.5]])

In [96]:
np.mean(a2)

3.65

In [97]:
np.max(a2)

6.5

In [98]:
np.min(a2)

1.0

In [99]:
# Standard Deviation: Measure of how spread out a group of numbers is from the mean

np.std(a2)

1.8264263832230778

In [100]:
# variance = measure of the average degree to which each number is different from the mean

# Higher Variance = wider range of numbers
# Lower Variance = lower range of numbers

np.var(a2)

3.3358333333333334

In [ ]:
# Standard Deviation  = square-root of variance!

np.sqrt(np.var(a2))