## Numpy Notebook:

Topics:
1. Useful Functions
2. NumPy datatypes and Attributes (ndarray)
3. creating arrays
4. viewing arrays and matrices
5. manipulating and comparing arrays
6. sorting arrays
7. use cases

In [1]:
import numpy as np

## Datatypes and Attributes:

In [2]:
# Numpy's main datatype is ndarray!

a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2.0, 3.3],
               [4.1, 5, 6.5]])

a3 = np.array([[[1, 2, 3], [4, 5, 6]],
               [[7, 8, 9], [10, 11, 12]],
               [[13, 14, 15], [16, 17, 18]]])


a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4.1, 5. , 6.5]])

In [6]:
# attributes:

a1.shape

(3,)

In [7]:
a2.shape

(2, 3)

In [8]:
a3.shape

(3, 2, 3)

In [9]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [10]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [11]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [12]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

## Create a Dataframe from a Numpy Array

In [14]:
import pandas as pd

df = pd.DataFrame(a2)

In [15]:
df

0    1    2
0  1.0  2.0  3.3
1  4.1  5.0  6.5

## Creating Random Arrays ASAP

In [16]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [17]:
sample_array.dtype

dtype('int64')

In [18]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
ones.dtype

dtype('float64')

In [20]:
type(ones)

numpy.ndarray

In [21]:
zeros = np.zeros((2, 3))

In [22]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [24]:
random_array = np.random.randint(0, 100, size=(3, 5))
random_array

array([[73, 43, 64, 32, 26],
       [74, 16, 71, 70, 75],
       [23, 35,  5, 65, 19]])

In [25]:
random_array.size

15

In [26]:
random_array.shape

(3, 5)

In [27]:
random_float_arr = np.random.random((5, 3))
random_float_arr

array([[0.26376265, 0.18057483, 0.64340888],
       [0.86741789, 0.01965457, 0.04370071],
       [0.72535083, 0.77140675, 0.21392734],
       [0.12302672, 0.36669319, 0.02708346],
       [0.59638909, 0.59661379, 0.46427543]])

In [28]:
random_float_arr.shape

(5, 3)

In [29]:
random_float_arr_new = np.random.rand(5, 3)
random_float_arr_new

array([[0.94106658, 0.2977698 , 0.55667651],
       [0.63768534, 0.5852948 , 0.46503702],
       [0.70646568, 0.73821434, 0.03279065],
       [0.51326764, 0.85763118, 0.20324501],
       [0.65097421, 0.76498097, 0.33518639]])

In [30]:
# Pseudo Random numbers:
np.random.seed(seed = 0)

In [31]:
np.random.seed(seed = 0) # now our "random" data doesnt change
random_arr_4 = np.random.randint(10, size=(5, 3))
random_arr_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [32]:
random_arr_4.shape

(5, 3)

np.random.seed() helps us to reproduce our random numbers and get same results even if someone else tries to run our notebook

In [33]:
np.random.seed(7)
random_arr_5 = np.random.random((5, 3))
random_arr_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [34]:
random_arr_5 = np.random.random((5, 3))
random_arr_5

# we observe different values

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])

## Viewing Arrays and Matrices

In [35]:
# Finding unique numbers in our ndarray

np.unique(random_arr_4)  # we get 0 to 9 as we have specified upper limit as 10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
a1

array([1, 2, 3])

In [37]:
a2

array([[1. , 2. , 3.3],
       [4.1, 5. , 6.5]])

In [38]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [39]:
a1[0]

1

In [40]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
a2[0]

array([1. , 2. , 3.3])

In [42]:
a2[1]

array([4.1, 5. , 6.5])

In [43]:
a3[2]

array([[13, 14, 15],
       [16, 17, 18]])

In [44]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [45]:
a3.shape

(3, 2, 3)

In [48]:
a3[:3,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]],

       [[13, 14],
        [16, 17]]])

array = np.rand.randint(upper-limit_of_num, size=(2 sets of final matrices ,three_matrices in one bracket ,rows ,cols))

In [49]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))

a4

array([[[[6, 7, 7, 9, 3],
         [0, 7, 7, 7, 0],
         [5, 4, 3, 1, 3],
         [1, 3, 4, 3, 1]],

        [[9, 5, 9, 1, 2],
         [3, 2, 2, 5, 7],
         [3, 0, 9, 9, 3],
         [4, 5, 3, 0, 4]],

        [[8, 6, 7, 2, 7],
         [3, 8, 6, 6, 5],
         [6, 5, 7, 1, 5],
         [4, 4, 9, 9, 0]]],


       [[[6, 2, 6, 8, 2],
         [4, 1, 6, 1, 5],
         [1, 6, 9, 8, 6],
         [5, 9, 7, 5, 4]],

        [[9, 6, 8, 1, 5],
         [5, 8, 3, 7, 7],
         [9, 4, 7, 5, 9],
         [6, 2, 0, 5, 3]],

        [[0, 5, 7, 1, 8],
         [4, 9, 0, 2, 0],
         [7, 6, 2, 9, 9],
         [5, 1, 0, 0, 9]]]])

In [50]:
a4.shape

(2, 3, 4, 5)

In [51]:
a4.ndim

4

In [52]:
# get first 4 numbers of the innermost arrays:

a4[:, :, :, :4]

array([[[[6, 7, 7, 9],
         [0, 7, 7, 7],
         [5, 4, 3, 1],
         [1, 3, 4, 3]],

        [[9, 5, 9, 1],
         [3, 2, 2, 5],
         [3, 0, 9, 9],
         [4, 5, 3, 0]],

        [[8, 6, 7, 2],
         [3, 8, 6, 6],
         [6, 5, 7, 1],
         [4, 4, 9, 9]]],


       [[[6, 2, 6, 8],
         [4, 1, 6, 1],
         [1, 6, 9, 8],
         [5, 9, 7, 5]],

        [[9, 6, 8, 1],
         [5, 8, 3, 7],
         [9, 4, 7, 5],
         [6, 2, 0, 5]],

        [[0, 5, 7, 1],
         [4, 9, 0, 2],
         [7, 6, 2, 9],
         [5, 1, 0, 0]]]])

In [53]:
a4[:, :, :, :3]

array([[[[6, 7, 7],
         [0, 7, 7],
         [5, 4, 3],
         [1, 3, 4]],

        [[9, 5, 9],
         [3, 2, 2],
         [3, 0, 9],
         [4, 5, 3]],

        [[8, 6, 7],
         [3, 8, 6],
         [6, 5, 7],
         [4, 4, 9]]],


       [[[6, 2, 6],
         [4, 1, 6],
         [1, 6, 9],
         [5, 9, 7]],

        [[9, 6, 8],
         [5, 8, 3],
         [9, 4, 7],
         [6, 2, 0]],

        [[0, 5, 7],
         [4, 9, 0],
         [7, 6, 2],
         [5, 1, 0]]]])

In [54]:
a4[:, :, :, :1]

array([[[[6],
         [0],
         [5],
         [1]],

        [[9],
         [3],
         [3],
         [4]],

        [[8],
         [3],
         [6],
         [4]]],


       [[[6],
         [4],
         [1],
         [5]],

        [[9],
         [5],
         [9],
         [6]],

        [[0],
         [4],
         [7],
         [5]]]])