## Numpy Notebook:

Topics:
1. Useful Functions
2. NumPy datatypes and Attributes (ndarray)
3. creating arrays
4. viewing arrays and matrices
5. manipulating and comparing arrays
6. sorting arrays
7. use cases

In [1]:
import numpy as np

## Datatypes and Attributes:

In [2]:
# Numpy's main datatype is ndarray!

a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2.0, 3.3],
               [4.1, 5, 6.5]])

a3 = np.array([[[1, 2, 3], [4, 5, 6]],
               [[7, 8, 9], [10, 11, 12]],
               [[13, 14, 15], [16, 17, 18]]])


a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4.1, 5. , 6.5]])

In [6]:
# attributes:

a1.shape

(3,)

In [7]:
a2.shape

(2, 3)

In [8]:
a3.shape

(3, 2, 3)

In [9]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [10]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [11]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [12]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

## Create a Dataframe from a Numpy Array

In [14]:
import pandas as pd

df = pd.DataFrame(a2)

In [15]:
df

0    1    2
0  1.0  2.0  3.3
1  4.1  5.0  6.5

## Creating Random Arrays ASAP

In [16]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [17]:
sample_array.dtype

dtype('int64')

In [20]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
ones.dtype

dtype('float64')

In [22]:
type(ones)

numpy.ndarray

In [23]:
zeros = np.zeros((2, 3))

In [24]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [27]:
random_array = np.random.randint(0, 100, size=(3, 5))
random_array

array([[25, 32, 79, 14, 83],
       [ 6, 73,  7, 52, 52],
       [91, 70, 98,  0, 72]])

In [28]:
random_array.size

15

In [29]:
random_array.shape

(3, 5)

In [32]:
random_float_arr = np.random.random((5, 3))
random_float_arr

array([[0.06701414, 0.53624466, 0.49324118],
       [0.5663843 , 0.7771409 , 0.94762842],
       [0.4214985 , 0.59101451, 0.35905467],
       [0.61368824, 0.27543389, 0.60994407],
       [0.09168321, 0.07541729, 0.65356945]])

In [33]:
random_float_arr.shape

(5, 3)

In [34]:
random_float_arr_new = np.random.rand(5, 3)
random_float_arr_new

array([[0.3234286 , 0.96787375, 0.24529158],
       [0.82174782, 0.96796953, 0.14858775],
       [0.82771988, 0.58625412, 0.08924593],
       [0.88621673, 0.91580361, 0.85400226],
       [0.09371578, 0.37661717, 0.46309272]])

In [35]:
# Pseudo Random numbers:
np.random.seed()