## Numpy Notebook:

Topics:
1. Useful Functions
2. NumPy datatypes and Attributes (ndarray)
3. creating arrays
4. viewing arrays and matrices
5. manipulating and comparing arrays
6. sorting arrays
7. use cases

In [1]:
import numpy as np

## Datatypes and Attributes:

In [2]:
# Numpy's main datatype is ndarray!

a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2.0, 3.3],
               [4.1, 5, 6.5]])

a3 = np.array([[[1, 2, 3], [4, 5, 6]],
               [[7, 8, 9], [10, 11, 12]],
               [[13, 14, 15], [16, 17, 18]]])


a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4.1, 5. , 6.5]])

In [6]:
# attributes:

a1.shape

(3,)

In [7]:
a2.shape

(2, 3)

In [8]:
a3.shape

(3, 2, 3)

In [9]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [10]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [11]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [12]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

## Create a Dataframe from a Numpy Array

In [14]:
import pandas as pd

df = pd.DataFrame(a2)

In [15]:
df

0    1    2
0  1.0  2.0  3.3
1  4.1  5.0  6.5